name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  docker-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: |
          docker build -t market-magic/ingestion ./services/ingestion
          docker build -t market-magic/modeling ./services/modeling
          docker build -t market-magic/serving ./services/serving
          docker build -t market-magic/api ./services/api
      - name: Package Helm chart
        run: helm package infra/helm/market-magic

  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: docker-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build static site
        env:
          NEXT_PUBLIC_BASE_PATH: /${{ github.event.repository.name }}
        run: |
          cd frontend
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
