name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: pip install ruff mypy pytest

      - name: Lint & Typecheck
        continue-on-error: true
        run: |
          ruff check .
          mypy services/modeling || true

      - name: Run tests
        run: pytest -q
